default: &default
  adapter: postgresql
  encoding: unicode
  host: card-dev.cgeos2quecpn.us-east-1.rds.amazonaws.com
  username: card
  password: '1234567890'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_sekka_development

test:
  <<: *default
  database: api_sekka_test

production:
  <<: *default
  database: api_sekka_production
